### ISSUE TITLE
3000 rows and 60 columns causing crash of plugin

### ISSUE THREAD

**Issue by clarkedesign** [FriendsOfCake/cakephp-csvview#142]
We're using your plugin and all works fine for smaller amounts of data.

We can export all rows and few columns (say up to 30)
We can export all columns for just a few rows (say 600)

BUT we cannot export 3000 rows and 60 columns.

An Internal Error Has Occurred
Error: An Internal Error Has Occurred.

Is there anything we can update to make this plugin work with a few more rows and columns please.

**Comment by dereuromark** [comment]
Quick-fix:
Raise your memory limit to what is needed at runtime for this action

otherwise, you need to paste details on what is going on here.

As for my initial assumption, you can also look into ways how to leverage
"PHP Stream filtering capabilities" similar to 
https://csv.thephpleague.com/9.0/connections/filters/

**Comment by clarkedesign** [comment]
Thanks for this, bit more memory seems to have helped :-)
